-- Generated by ~/.config/caelestia/scripts/wezterm-theme.py
-- DO NOT EDIT — regenerated on every wallpaper/theme change.
return {
	custom_colors = {
		red     = "#eeeeee",
		cyan    = "#9e9e9e",
		magenta = "#c6c6c6",
		yellow  = "#e1dee5",
		green   = "#B5CCBA",
	},

	status = {
		workspace  = "#ababab",
		mode       = "#9e9e9e",
		leader     = "#c6c6c6",
		leader_fg  = "#404040",
		cwd        = "#767676",
		process    = "#ababab",
		clock      = "#9e9e9e",
		battery    = "#B5CCBA",
	},

	tab_bar = {
		bg        = "#000000",
		fg        = "#e5e5e5",
		gray      = "#767676",
		active_bg = "#c6c6c6",
		active_fg = "#404040",
	},

	terminal = {
		ansi          = { "#343434", "#af78e3", "#e5c4c7", "#ece4e6", "#a6aabe", "#b5a3ce", "#b5cce6", "#d8d8d8" },
		brights       = { "#a3a3a3", "#c198e5", "#e3dbdb", "#f4f4f4", "#c1c0c5", "#c9b9d9", "#d1dde9", "#ffffff" },
		background    = "#0e0e0e",
		foreground    = "#e5e5e5",
		cursor_bg     = "#c6c6c6",
		cursor_fg     = "#404040",
		cursor_border = "#c6c6c6",
		selection_bg  = "#464646",
		selection_fg  = "#d0d0d0",
	},
}
