-- Generated by ~/.config/caelestia/scripts/wezterm-theme.py
-- DO NOT EDIT — regenerated on every wallpaper/theme change.
return {
	custom_colors = {
		red     = "#225DB1",
		cyan    = "#3D83CB",
		magenta = "#5486B8",
		yellow  = "#1F60C1",
		green   = "#4875AB",
	},

	status = {
		workspace = "#3276C5", -- "main" label: dark accent on light bars, bright on dark
		mode      = "#3D83CB",
		leader    = "#5486B8",            -- leader pill background (filled, like active tab)
		leader_fg = "#c1c3c5", -- text on the leader pill
		cwd       = "#3276C5",
		process   = "#1F60C1",
		clock     = "#3D83CB",
		battery   = "#4875AB",
	},

	tab_bar = {
		bg        = "#0a1017", -- bar / inactive / new-tab background
		fg        = "#c1c3c5", -- text on the bar
		gray      = "#59626d",            -- dimmed inactive text / hover bg
		active_bg = "#3D83CB",            -- selected tab background (accent)
		active_fg = "#c1c3c5", -- selected tab text

		-- Custom tab bar colors (tab-title.lua)
		default_bg  = "#0a1017", -- inactive tab body (near-black, blends with bar)
		default_fg  = "#c1c3c5", -- inactive tab text
		hover_bg    = "#5486B8",            -- hovered tab body (magenta/blue)
		hover_fg    = "#c1c3c5", -- hovered tab text
		active_bg2  = "#3276C5",  -- active tab body (orange, pops)
		active_fg2  = "#0a1017", -- active tab text
		unseen      = "#225DB1",            -- unseen output badge (red)
		progress_ok = "#4875AB",            -- progress success (green)
		progress_err = "#225DB1",           -- progress error (red)
		progress_ind = "#c1c3c5", -- progress indeterminate (light)
	},

	terminal = {
		ansi          = { "#343434", "#8383ff", "#40dfee", "#75fcdd", "#7cb2c8", "#7baeea", "#83d5e7", "#ccdcd6" },
		brights       = { "#9aa59f", "#a29eff", "#66f0ff", "#c9fff3", "#a6c6d1", "#a2c0f7", "#8ae9fc", "#ffffff" },
		background    = "#0b0f11",
		foreground    = "#dee7ed",
		cursor_bg     = "#a3cce3",
		cursor_fg     = "#184557",
		cursor_border = "#a3cce3",
		selection_bg  = "#2d576a",
		selection_fg  = "#c1e9ff",
	},
}
