local M = {}

-- Tab bar color styling. All hexes come from theme.lua (the single themed-color
-- source, generated by ~/.config/yasb/colorScheme.ps1).
function M.apply(config, constants)
	local t = constants.theme.tab_bar
	config.colors = {
		tab_bar = {
			background = t.bg,
			active_tab = {
				bg_color = t.active_bg,
				fg_color = t.active_fg,
				intensity = "Bold",
				underline = "None",
			},
			inactive_tab = {
				bg_color = t.bg,
				fg_color = t.gray,
			},
			inactive_tab_hover = {
				bg_color = t.gray,
				fg_color = t.fg,
			},
			new_tab = {
				bg_color = t.bg,
				fg_color = t.fg,
			},
		},
	}
end

return M
