local M = {}

-- Colors from theme.lua.
-- Linux: generated by ~/.config/caelestia/scripts/wezterm-theme.py (includes terminal section)
-- Windows: generated by ~/.config/yasb/colorScheme.ps1 from theme.lua.template (tab_bar only)
function M.apply(config, constants)
	local t = constants.theme.tab_bar
	local tr = constants.theme.terminal

	local colors = {
		tab_bar = {
			background = t.bg,
			active_tab = {
				bg_color = t.active_bg,
				fg_color = t.active_fg,
				intensity = "Bold",
				underline = "None",
			},
			inactive_tab = {
				bg_color = t.bg,
				fg_color = t.gray,
			},
			inactive_tab_hover = {
				bg_color = t.gray,
				fg_color = t.fg,
			},
			new_tab = {
				bg_color = t.bg,
				fg_color = t.fg,
			},
		},
	}

	if tr then
		colors.ansi = tr.ansi
		colors.brights = tr.brights
		colors.background = tr.background
		colors.foreground = tr.foreground
		colors.cursor_bg = tr.cursor_bg
		colors.cursor_fg = tr.cursor_fg
		colors.cursor_border = tr.cursor_border
		colors.selection_bg = tr.selection_bg
		colors.selection_fg = tr.selection_fg
	end

	config.colors = colors
end

return M
